name: percobaan1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0

  # iOS style icons
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.4.9

  # HTTP requests
  http: ^1.1.0

  # Local Storage untuk token
  shared_preferences: ^2.2.2

  # JSON Serialization
  json_annotation: ^4.8.1

  # Routing
  go_router: ^17.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # ===============================
  # Assets (gambar & ilustrasi)
  # ===============================
  assets:
    - assets/images/                # semua gambar di folder ini otomatis terdaftar
    # contoh spesifik jika ingin per file:
    # - assets/images/anakanakpolos.png
    # - assets/images/school_bg.jpg

  # ===============================
  # Fonts (opsional untuk tampilan profesional)
  # ============================
